### ISSUE TITLE
How can we use existing sessions with this package ? (Is there an option to pass sessionId through the options)

### ISSUE THREAD

**Issue by rajatKumarr** [zytedata/zyte-smartproxy-plugin#1]

**Comment by geronsv** [comment]
Hi @rajatKumarr 
Thanks for the feedback!
We've just published the new version of this package with new `spm_session_id` parameter. Check it out!

Also consider our new [Smart Browser](https://www.zyte.com/smart-browser-api-anti-fingerprinting/) which have a browser built-in.

**Comment by rajatKumarr** [comment]
@geronsv can this be added as option in puppeter.launch instead of options of SmartProxyManager as sessionId can be changed for multiple requests and we normally use puppeter.use once to plugging in the manager plugin ?

**Comment by geronsv** [comment]
Sounds great @rajatKumarr !
Have added it just now.
